### ISSUE TITLE
[BUG]: conversation.external does not work

### ISSUE THREAD

**Issue by Gercov** [grammyjs/conversations#1]
![image](https://user-images.githubusercontent.com/12952387/167264609-81084585-cde9-4af0-9593-06746b2e5124.png)

**Comment by KnorpelSenf** [comment]
Unable to reproduce.

**Comment by Gercov** [comment]
> Unable to reproduce.

```
import { type Conversation } from '@grammyjs/conversations';
import { phrases } from 'shared/config';
import { generateAuthLink, validateAuthCode } from 'shared/lib';
import { MyContext } from 'shared/typicode';

type MyConversation = Conversation<MyContext>;

export const auth = async (conversation: MyConversation, ctx: MyContext) => {
  await ctx.reply(phrases.greeting, {
    reply_markup: {
      inline_keyboard: [
        [{ text: 'Auth', url: generateAuthLink() }],
      ],
    },
  });
  ctx = await conversation.wait();
  while (ctx.message) {
    if (ctx.message?.text?.startsWith('/start')) {
      console.log(ctx.message.text)
      ctx = await conversation.wait()
    } else {
      await ctx.reply('Auth for continue');
      ctx = await conversation.wait();
    }
  }
};

```

**Comment by KnorpelSenf** [comment]
The solution is very simple. When you enter your conversation, you must pass the name of your function. However, what you did is to create a lambda, so it does name have a name (even not if you store the lambda in a variable with a name).

You can either use a real function:

```ts
function auth(conversation: MyConversation, ctx: MyContext) {
  // rest
}
```
Or you can pass a custom name when installing the function and use it to enter the function:

```ts
bot.use(createConversation(auth, "new-name"));

bot.command("/start", ctx => ctx.conversation.enter("new-name"))
```

When either of these modifications are performed, your code works again.

**Comment by KnorpelSenf** [comment]
I will add another safety protection that detects when this mistake is made. That way, the plugin can throw a meaningful error message, so that other people will not be stuck with the same problem. Thanks for reporting!
