### ISSUE TITLE
docs: Decide on whether ConversationFlavor is additive or transformative

### ISSUE THREAD

**Issue by KnightNiwrem** [grammyjs/conversations#105]
ConversationFlavor in code follows a Transformative flavor pattern, while it is used like an Additive flavor in documentation.

This happens to work in many instances, but not where the transformation is necessary (dependent on the type ternary predicate expression).

Ref: https://t.me/grammyjs/236022

**Comment by KnorpelSenf** [comment]
I guess the docs need to be updated. We are going to throw out the idea of additive flavours for 2.0 anyway.
