### ISSUE TITLE
Update error message when session is unavailable

### ISSUE THREAD

**Issue by Loskir** [grammyjs/conversations#109]
As discussed in https://t.me/grammyjs/244616

> at least we can update conversations so that the error text is more clear, like
>> Conversations encountered an update without a session: ${ctx.updateType}. In order to handle this type of update inside of conversation, update your getSessionKey function. Or you can skip this update for conversations, like this: bot.filter((ctx) => !ctx.has(...)).use(conversations())

**Comment by KnorpelSenf** [comment]
This is irrelevant since v2.
