### ISSUE TITLE
`otherwise` executed immeditely

### ISSUE THREAD

**Issue by matmilbury** [grammyjs/conversations#115]
I want to exit the conversation if a user does something else other than answering my inline keyboard.

This works as expected

```ts
try {
  await conversation.waitForCallbackQuery(
    ['yes', 'no'],
    () => { throw new Error('exit') }
  )
} catch {
  return
}
```

but this does not because `otherwise` function is executed as soon as the conversation is entered, exiting immediately:
```ts
try {
  await conversation.waitForCallbackQuery(
    ['yes', 'no'],
    { otherwise: () => { throw new Error('exit') }}
  )
} catch {
  return
}

**Comment by KnorpelSenf** [comment]
Can you show more code? I cannot reproduce this.

**Comment by matmilbury** [comment]
my code since changed and I can't reproduce anymore either. Sorry :grimacing:
