### ISSUE TITLE
bugs: Why isn't the bot responding?

### ISSUE THREAD

**Issue by sukbearai** [grammyjs/conversations#128]
![image](https://github.com/user-attachments/assets/8514d49d-1228-4b4f-9976-fd8e4a2a87ea)

```ts
import type { FFContext, FFConversation } from '../types'

async function twitterScraper(conversation: FFConversation, ctx: FFContext) {
  await ctx.reply('Hi there! What is your name?!')
  const { message } = await conversation.wait()
  await ctx.reply(`Welcome to the chat, ${message!.text}!`)
}

export default twitterScraper

```

**Comment by KnorpelSenf** [comment]
There are a million possible reasons for this and very few of them are related to this plugin. You need to provide a lot more info.

**Comment by sukbearai** [comment]
> There are a million possible reasons for this and very few of them are related to this plugin. You need to provide a lot more info.

There's a test repository https://github.com/johannschopplich/finanzfluss-telegram-bot.pls help me🙏

**Comment by KnorpelSenf** [comment]
There is a good chance that the issue isn't in your code so I won't spend hours reading through the entire project, sorry. Try providing an https://sscce.org.
