### ISSUE TITLE
Old session data is read by dynamic menu if set before during the conversation

### ISSUE THREAD

**Issue by daniharo** [grammyjs/conversations#14]
When setting `ctx.session.something` inside a conversation before sending a dynamic menu, the dynamic menu will see an old value of the session.

Try this CodeSandbox:
[![Edit grammy-conversations-session-issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bitter-sound-kiprz0?fontsize=14&hidenavigation=1&theme=dark)

Button is "-", when it should be "Hi".

**Comment by daniharo** [comment]
Just updated the sandbox with that workaround, same result.

**Comment by KnorpelSenf** [comment]
Can you check if #15 fixes the problem?

**Comment by daniharo** [comment]
Yes!!! Bye grammyjs/router :P
