### ISSUE TITLE
Can it be used with LazySessionFlavor?

### ISSUE THREAD

**Issue by habdenscrimen** [grammyjs/conversations#3]
When I'm trying to create a custom context by extending both `LazySessionFlavor` and `ConversationFlavor`, I get an error:

```
Interface 'CustomContext' cannot simultaneously extend types 'LazySessionFlavor<BotSessionData>' and 'ConversationFlavor'.
  Named property 'session' of types 'LazySessionFlavor<BotSessionData>' and 'ConversationFlavor' are not identical.
```

Is it possible to use Conversations with LazySession?

**Comment by KnorpelSenf** [comment]
Not yet, but all plugins should support lazy sessions, so this one will, too.

**Comment by habdenscrimen** [comment]
Thanks!

**Comment by KnorpelSenf** [comment]
@habdenscrimen can you review #9?
