### ISSUE TITLE
Using conversations with multi sessions

### ISSUE THREAD

**Issue by askador** [grammyjs/conversations#61]
**Problem**: An error occcurs after conversation is finished
**Error**: `TypeError: Cannot delete property 'conversation' of #<Object>
       at node_modules\@grammyjs\conversations\out\conversation.js:304:17`
**Expected behavior**: Conversation finishes safely
**Bug representation**: https://pastebin.com/eHuz9JbS

**Comment by KnorpelSenf** [comment]
I was wrong, it cannot be fixed in the core library haha :D

**Comment by KnorpelSenf** [comment]
@askador please review #61
