### ISSUE TITLE
@grammy/conversations v1.1.1 session parse error

### ISSUE THREAD

**Issue by sc0ch** [grammyjs/conversations#73]
Reprocude:
--------------------------------------
import { Bot, session } from "grammy"
import { conversations, createConversation } from '@grammyjs/conversations'
const token = 'XXXXXXXXXXXXXXXXXXXXXXX'
const bot = new Bot(token)
function initial() {
  return { }
}
bot.use(session({ initial }))
bot.use(conversations())
let c = async function (conversation, ctx) {
	await ctx.reply("Some message");
	const { message } = await conversation.waitFrom(ctx.from)
	console.log(message)
} 
bot.use(createConversation(c))
bot.on('message', ctx => {
	ctx.conversation.enter('c')
})
bot.start()
--------------------------------------

After any message to bot i've got:

/data/____/node_modules/@grammyjs/conversations/out/conversation.js:357
                if (session.conversation[id].length === 0) {
                                             ^

TypeError: Cannot read properties of undefined (reading 'length')
    at ctx.conversation.enter (/data/____/node_modules/@grammyjs/conversations/out/conversation.js:357:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

OS: Ubuntu 22.04 LTS
NodeJS: 19.7.0
Grammy: 1.15.2

@grammy/conversations v1.0.3 - have not that issue.

**Comment by sc0ch** [comment]
Yep... forgot await, sorry. 
False issue. Close please.

**Comment by KnorpelSenf** [comment]
You're not the first one to forget this. I'll think about how to detect and prevent such mistakes library-side. Glad it's fixed!
