### ISSUE TITLE
Use with files plugin

### ISSUE THREAD

**Issue by ralphilius** [grammyjs/conversations#87]
I've posted here https://github.com/grammyjs/files/issues/4, but I reposted here for more exposure.

The files plugin use `bot.api.config.use` for configuration. Is it safe to use `hydrateFiles(token)` within `conversation.run`?

**Comment by KnorpelSenf** [comment]
You can call `ctx.api.config.use` inside `conversation.run`, yes. Safe in what way?

**Comment by ralphilius** [comment]
> You can call `ctx.api.config.use` inside `conversation.run`, yes. Safe in what way?

Ah, I just mean is it possible to use inside that function. Thanks for clarifying.
