### ISSUE TITLE
Can I start a conversation from a `callbackQuery`? 

### ISSUE THREAD

**Issue by dadatuputi** [grammyjs/conversations#92]
In all the documentation I'm seeing `conversation.enter` in a `bot.command` function. I'm trying to start a conversation as a result of a button push, but when I do, the context doesn't have the registered conversations, with the error `Error: The conversation 'greeting' has not been registered! Known conversations are: `.

**Comment by dadatuputi** [comment]
For added context about what I'm trying to do - 

I have a folder of telegram commands - each one has exported objects of name, description, and execute ([example](https://github.com/dadatuputi/xx_monitor_bot/blob/telegram/src/bots/telegram/commands/monitor.ts)).

In my bot init code, I register the execute object function as a command [here](https://github.com/dadatuputi/xx_monitor_bot/blob/14fb9ee51b46c610896d0aca084d78f4ae7bafb8/src/bots/telegram/index.ts#L55), and then register all the members of the `callbacks` and `convos` functions [here ](https://github.com/dadatuputi/xx_monitor_bot/blob/14fb9ee51b46c610896d0aca084d78f4ae7bafb8/src/bots/telegram/index.ts#L56-L59) and [here](https://github.com/dadatuputi/xx_monitor_bot/blob/14fb9ee51b46c610896d0aca084d78f4ae7bafb8/src/bots/telegram/index.ts#L60-L63).

This method works great for executing commands and callbacks, however when I have my callback try to enter a conversation, such as [here](https://github.com/dadatuputi/xx_monitor_bot/blob/14fb9ee51b46c610896d0aca084d78f4ae7bafb8/src/bots/telegram/commands/monitor.ts#L42), I get the error as above. 

I hope that helps. I may be missing something, or it may just be that it is impossible to do what I'm trying to do. 

Thanks for any advice.

**Comment by roziscoding** [comment]
The conversation has to be registered before the callback handler for it to work properly.
You receive this error because, when your handler runs, the conversation is not yet registered, thus it doesn't exist.

**Comment by dadatuputi** [comment]
Yep - that was it! I swapped the location of my for loop registering conversations and placed it above the loop registering callbacks. 

Thanks for the quick answer.
