### ISSUE TITLE
Does not wait for user input with gramjs

### ISSUE THREAD

**Issue by m0x61h0x64i** [grammyjs/conversations#98]
im using conversations package to create a session using gramjs client.start function (for phone number, code and password)

while i want user phone number it gives me error this is my code :
```
phoneNumber: async () => {
                        console.log(9)
                        return await ctx.conversation.enter('getPhoneNumber')
                    }
```

phone number callback does not wait for conversations and then it throws error which says im getting undefined instead of phone number.

here is the full code :
https://github.com/m0x61h0x64i/telegram-session-sender

**Comment by KnorpelSenf** [comment]
This exact code has been discussed numerous times in the chat. The plugin works exactly as intended.

**Comment by m0x61h0x64i** [comment]
@KnorpelSenf after updating from js to ts, im now getting error which says phone number is invalid but i didnt even give it phone number, it shows that conversation package does  not wait for user input (phone number) in order for phoneNumber gramjs callback function be able to return the correct phone number.

code updated :
https://github.com/m0x61h0x64i/telegram-session-sender

**Comment by KnorpelSenf** [comment]
My answers stay the same. The plugin is not going to wait, no matter how many times you ask.
